apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}  # Number of MongoDB replicas
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # MongoDB image from values.yaml
        ports:
        - containerPort: {{ .Values.service.port }}  # Expose MongoDB port from values.yaml
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db  # MongoDB data directory
      volumes:
      - name: mongodb-storage
        emptyDir: {}  # Temporary storage for testing (use persistent volume for production)
